_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
                - 62
            "4": 3.8.20
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
criterion:
    value: gini
model:
    value: 1
random_state:
    value: 41
splitter:
    value: best
