wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1746540839
    t:
      1:
      - 5
      - 53
      - 55
      4: 3.8.20
      5: 0.12.14
      8:
      - 3
      - 5
      - 9
