wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1746640456
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.8.20
      5: 0.12.14
      8:
      - 1
      - 3
      - 5
criterion:
  desc: null
  value: entropy
model:
  desc: null
  value: 0
random_state:
  desc: null
  value: 41
splitter:
  desc: null
  value: random
